import "./globals.scss";
import type { Metadata } from "next";
import "ress";
import Header from "./Components/Header";
import { Noto_Sans_JP } from "next/font/google";

const NotoSans = Noto_Sans_JP({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className={NotoSans.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
